#! /bin/bash -xe

input="$1"
output="$2"
wrapper="$3"

for i in `seq 0 4`; do
    export wrapper${i}="$(afl_instance=${i} eval echo $(echo ${wrapper}))"
done

export AFL_SKIP_BIN_CHECK=1

tmux new-session -d        "${AFL_FUZZ} -i ${input} -o ${output} -M fuzzer0 -- ${wrapper0}; sleep 5" \; \
	split-window -h -d "${AFL_FUZZ} -i ${input} -o ${output} -S fuzzer1 -- ${wrapper1}; sleep 5" \; \
	split-window -d    "${AFL_FUZZ} -i ${input} -o ${output} -S fuzzer2 -- ${wrapper2}; sleep 5" \; \
	select-pane -R \; \
	split-window -d    "${AFL_FUZZ} -i ${input} -o ${output} -S fuzzer3 -- ${wrapper3}; sleep 5" \; \
	attach \;
